language: cpp

compiler:
  - gcc

script: 
  - g++ -c Object3D.cpp -o objected.o
  - g++ -c Model3D.cpp -o model3d.o
  - g++ -c GLSetup.cpp -o glsetup.o
  - g++ -c Matrix.cpp -o matrix.o
  - g++ -c picker.cpp -o picker.o
  - g++ -c staticgeom.cpp -o staticgeom.o
  - g++ -c RenderingContext.cpp -o renderingContext.o
  - g++ -c testing.cpp -o testing.o
  - g++ linuxmain.cpp -o main.exe

notifications:
  email: false