language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libglew-dev
      - freeglut3-dev
  env:
   - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

services:
  - docker

compiler:
  - gcc

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script: 
  - mkdir lib
  - g++-7 -O2 -c -std=c++11 Object3D.cpp -o lib/objected.o
  - g++-7 -O2 -c -std=c++11 Model3D.cpp -o lib/model3d.o
  - g++-7 -O2 -c -std=c++11 GLSetup.cpp -o lib/glsetup.o
  - g++-7 -O2 -c -std=c++11 Matrix.cpp -o lib/matrix.o
  - g++-7 -O2 -c -std=c++11 picker.cpp -o lib/picker.o
  - g++-7 -O2 -c -std=c++11 staticgeom.cpp -o lib/staticgeom.o
  - g++-7 -O2 -c -std=c++11 RenderingContext.cpp -o lib/renderingContext.o
  - g++-7 -O2 -c -std=c++11 testing.cpp -o lib/testing.o
  - g++-7 -O2 -std=c++11 -L lib/* -L /usr/include/GL/* -L /usr/lib/libglut/* linuxmain.cpp -o main.exe
  - docker exec -it emscripten em++ -O2 -c -std=c++11 Object3D.cpp -o lib/objected.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 Model3D.cpp -o lib/model3d.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 GLSetup.cpp -o lib/glsetup.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 Matrix.cpp -o lib/matrix.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 picker.cpp -o lib/picker.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 staticgeom.cpp -o lib/staticgeom.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 RenderingContext.cpp -o lib/renderingContext.bc
  - docker exec -it emscripten em++ -O2 -c -std=c++11 testing.cpp -o lib/testing.bc
  - docker exec -it emscripten em++ -O2 -std=c++11 -L lib/* linuxmain.cpp -o glworld.js -s DEMANGLE_SUPPORT=1 -s FULL_ES2=1 -s ALLOW_MEMORY_GROWTH=1 --preload-file fragshader.txt --preload-file vertshader.txt --preload-file sfragshader.txt --preload-file svertshader.txt --preload-file nfragshader.txt --preload-file nvertshader.txt --preload-file assets/crane.3dm --preload-file assets/landscape-nouv.3dm --preload-file assets/monument.3dm --preload-file textures/grass.jpg --preload-file textures/btile.jpg --preload-file textures/lbtile.jpg --preload-file textures/green.bmp --preload-file textures/rust.jpg --preload-file textures/glass.jpg --preload-file textures/metal.jpg 

notifications:
  email: false