language: cpp

compiler:
  - gcc
  - clang

script: 
  - CXX -c Object3D.cpp -o objected.o
  - CXX -c Model3D.cpp -o model3d.o
  - CXX -c GLSetup.cpp -o glsetup.o
  - CXX -c Matrix.cpp -o matrix.o
  - CXX -c picker.cpp -o picker.o
  - CXX -c staticgeom.cpp -o staticgeom.o
  - CXX -c RenderingContext.cpp -o renderingContext.o
  - CXX -c testing.cpp -o testing.o
  - CXX linuxmain.cpp -o main.exe

notifications:
  email: false