# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  release_build:
    name: 'Release Build'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v6
      # Runs a single command using the runners shell
      - name: Build
        run: em++ -O2 -std=c++11 Object3D.cpp Model3D.cpp GLSetup.cpp Matrix.cpp picker.cpp staticgeom.cpp RenderingContext.cpp testing.cpp linuxmain.cpp -o index.html -s DEMANGLE_SUPPORT=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s ALLOW_MEMORY_GROWTH=1 --preload-file fragshader.txt --preload-file vertshader.txt --preload-file sfragshader.txt --preload-file svertshader.txt --preload-file nfragshader.txt --preload-file nvertshader.txt --preload-file assets/crane.3dm --preload-file assets/landscape-nouv.3dm --preload-file assets/monument.3dm --preload-file textures/grass.jpg --preload-file textures/btile.jpg --preload-file textures/lbtile.jpg --preload-file textures/green.bmp --preload-file textures/rust.jpg --preload-file textures/glass.jpg --preload-file textures/metal.jpg --preload-file textures/negx.jpg --preload-file textures/posx.jpg --preload-file textures/negx.jpg --preload-file textures/negz.jpg --preload-file textures/posz.jpg --preload-file textures/posy.jpg
        
      - name: linux build
        run: g++-7 -O2 -std=c++11 -L /usr/include/GL/* -L /usr/lib/libglut/* Object3D.cpp Model3D.cpp GLSetup.cpp Matrix.cpp picker.cpp staticgeom.cpp RenderingContext.cpp testing.cpp linuxmain.cpp -o main -lglut -lGL -lGLU -lGLEW
        
        
      - name: Upload index.html
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: index.html # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: index.html   
          
      - name: Upload index.js
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: index.js # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: index.js
          
      - name: Upload main
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: main # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: main
