# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
  # setup cmake 
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install cmake
        run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev wget -y
      - name: download freeglut3-dev
        run: wget -O freeglut-3.6.0.tar.gz https://github.com/freeglut/freeglut/releases/download/v3.6.0/freeglut-3.6.0.tar.gz
      - name: extract freeglut3-dev
        run: tar -xvf freeglut-3.6.0.tar.gz
      - name: CMake Action
        uses: threeal/cmake-action@main
